### ISSUE TITLE
Load Balance divisions 

### ISSUE THREAD

**Issue by eladyaniv01** [aiarena/aiarena-web#103]
This is a tricky one because
 we don't need this RIGHT NOW ( we can manually balance the divisions with our current volume)
and it could delay the multi ladder deployment and sc2ai merge 

- [ ]  Load balancing mechanism ( for when the number of active bots change,  reduce divisions or expand to more divisions)

Perhaps split this into smaller tickets?

**Comment by lladdy** [comment]
Fulfilled by https://github.com/aiarena/aiarena-web/pull/301
