### ISSUE TITLE
Abbreviate timestamps like 1 day, 1 hour ago

### ISSUE THREAD

**Issue by lladdy** [aiarena/aiarena-web#141]
`1 day, 1 hour ago` can instead be
 `1d 1h ago` or `1d 1h`

Or even only showing a single unit of time:
Example:
if less than an hour, display in minutes e.g. `32m`.
If over an hour but less than 1 day, show in hours e.g. `5h`
etc...

Currently we use natural time to generate the previously mentioned text.
https://docs.djangoproject.com/en/3.1/ref/contrib/humanize/#naturaltime

**Comment by Immodal** [comment]
Could probably just use [this](https://github.com/ollieglass/django-shortnaturaltime)?

![image](https://user-images.githubusercontent.com/13944193/101983101-bc97ec00-3ccc-11eb-82fb-e4b5fdb2e77b.png)
