### ISSUE TITLE
A bot can choose to play a different race than it has set in AI-arena

### ISSUE THREAD

**Issue by SimonPrins** [aiarena/aiarena-web#154]
The bot DroneDroneDrone is set as Zerg on ai-arena, but it has played some games as Terran:
https://aiarena.net/matches/414133/

The same goes for FourGateDev:
https://aiarena.net/matches/415428/

Ideally ai-arena should enforce the race picked on the website.
I believe this was discussed previously, but I am not sure whether this was actually implemented and is now bugged, or whether it has simply never been done.

**Comment by eladyaniv01** [comment]
ref proto https://github.com/Blizzard/s2client-proto/blob/master/s2clientprotocol/sc2api.proto#L212

**Comment by lladdy** [comment]
Recreated in the AC repo: https://github.com/aiarena/aiarena-client/issues/33
