### ISSUE TITLE
Option to hide inactive bots

### ISSUE THREAD

**Issue by Fidolina** [aiarena/aiarena-web#158]
The authors main page and drop down lists for requested matches etc, can get crowded with inactive bots since there is no option to actually delete a bot. Assuming there is no plan to allow for bots to be deleted, it would be great if there was an option to "filter" bots in order to remove the "background noise". Personally I want to be able to hide all my inactive bots from all interactions (main profile page, request game lists etc).

Maybe it would also be reasonable to offer an option to take your inactive bots completely our of commission, i.e make it so that others cannot request a match versus it. Maybe it should even be default that inactive bots are not eligible for match request by other authors.

**Comment by eladyaniv01** [comment]
Closed https://github.com/aiarena/aiarena-web/pull/165
