### ISSUE TITLE
Show recent match results on author page

### ISSUE THREAD

**Issue by SimonPrins** [aiarena/aiarena-web#172]
It would be nice to add the recent game results to an authors page, filtered so that it only includes games where (at least) one of the authors bots has participated.

In terms of the columns, I would use the same columns as the results page:
https://aiarena.net/results/

Pagination similar to the results page would also be nice.

**Comment by Immodal** [comment]
Might the profile page be a better spot? This seems like information that's more relevant to the author themself and they have to go there to cancel matches anyway.

**Comment by SimonPrins** [comment]
I thought about profile page, but I figure that, even if it is more relevant to the author themselves, it may still be interesting to some to view other peoples matches. That would be impossible if it is only on the profile page.

Alternatively it could maybe be added to both pages?
