### ISSUE TITLE
Dates on season graphs are wrong

### ISSUE THREAD

**Issue by spudde123** [aiarena/aiarena-web#177]
The dates on the graph don't make sense. Season 2 started in June 2020. The dates are wrong in all bot pages, but DominionDog for example was only added in December 2020.

https://aiarena.net/seasons/stats/181/dominiondog-season-2

![stats](https://user-images.githubusercontent.com/3307207/104834563-eedad180-58a8-11eb-8ea0-9552652dda9b.png)

**Comment by lladdy** [comment]
Guessing this is an issue with the stats gen.
