### ISSUE TITLE
can not get maps by the docs

### ISSUE THREAD

**Issue by guojiahuiEmily** [aiarena/aiarena-web#238]
the maps are used by your web is  DeathAura506. but there is no this map by your docs.

**Comment by lladdy** [comment]
Hi @guojiahuiEmily 
The correct maps can be found here: https://aiarena.net/wiki/maps/

I have updated the getting started page with this link.
Was the getting started page where you found the wrong details?

**Comment by guojiahuiEmily** [comment]
thank you. I got the map.

**Comment by guojiahuiEmily** [comment]
I can't find map "EverDreamLE.SC2Map".   please add it to some place

**Comment by LostLucidity** [comment]
@guojiahuiEmily Added link to Blizzard's map packs. You can get EverDreamLE.SC2Map some of the season links. There may be more than one version of same named maps that are incompatible between season, however.

**Comment by guojiahuiEmily** [comment]
thanks. but i can't find EverDreamLE.SC2Map in them. I need it to watch the replay of sc2ai.net.  Would you please share the maps used by sc2ai.net in github?

**Comment by LostLucidity** [comment]
@guojiahuiEmily Okay. I see what you mean. I'll have to upload them myself. I'll do that later today.

**Comment by LostLucidity** [comment]
@guojiahuiEmily Replaced the link with the ladder maps link. Try it now.

**Comment by guojiahuiEmily** [comment]
I found it. thank you. nice man.
