### ISSUE TITLE
How to make two ai combat in local pc by python

### ISSUE THREAD

**Issue by guojiahuiEmily** [aiarena/aiarena-web#240]
I want to watch and improve my bot by combat my two bot in my local pc by python.

How to do it?

**Comment by Immodal** [comment]
Hi Emily, I would suggest joining our discord server here: https://discord.gg/Emm5Ztz

Members are much more active there and will likely be able to answer your questions quickly. You can ask in the "setup-help" or channel specific to the framework you are using. Unfortunately I'm not familiar enough with this to be of much help.

**Comment by lladdy** [comment]
Closed - Not relevant to the website development.
