### ISSUE TITLE
please offer details for Initialization Failure	

### ISSUE THREAD

**Issue by guojiahuiEmily** [aiarena/aiarena-web#242]
1. My bot requset match. Got Initialization Failure. But I don't know what's the problem.
I download someone other's bot BluntLurkers. And upload to request match. Also got Initialization Failure.

My bot :   https://aiarena.net/bots/283/

How can I make my bot run normally.
My bot is based on sharpy-sc2. Is just one core file.  I run it ok on my Mac.

2. and that's the python version your aiarena client use to run ?

3. use what command to run my run.py to check?

**Comment by guojiahuiEmily** [comment]
and that's the python version your aiarena client use to run ?

**Comment by lladdy** [comment]
Hi @guojiahuiEmily,

Sorry for the slow reply. You'll usually get a much quicker reply on our Discord here in case you wish to join: https://discord.gg/Emm5Ztz

If you go to your bot's page, you can download your bot's error log in the list of played matches.

We're running Python 3.7.
You can see the DockerFile here: https://github.com/aiarena/aiarena-docker

The bot command is:
`python <bot_file> --GamePort <port> --StartPort <port> --LadderServer <server> --OpponentId <id>
You can see how the call to the bot is constructed here:
https://github.com/aiarena/aiarena-client/blob/50b25eb4838b6588d696ee46690c23bdcd234f8b/arenaclient/match/bot.py#L159

**Comment by lladdy** [comment]
Closing this - no longer needed.
