### ISSUE TITLE
Error uploading bot with data folder.

### ISSUE THREAD

**Issue by LostLucidity** [aiarena/aiarena-web#257]
Getting this error when trying to upload my bot with a data folder with an empty file.
![image](https://user-images.githubusercontent.com/14098964/116053082-462ad380-a648-11eb-8e64-ad59e1f592f1.png)
My Zip
![image](https://user-images.githubusercontent.com/14098964/116053118-4e830e80-a648-11eb-96bf-ce8e434d8df5.png)

Was following folder structure of the wiki.
https://aiarena.net/wiki/bot-development/getting-started/#wiki-toc-bot-zip

**Comment by lladdy** [comment]
How many times did you attempt and receive this message?
Are you using the normal website frontend through a browser?

**Comment by LostLucidity** [comment]
About 10 times, every time.
I'm using Firefox.
![image](https://user-images.githubusercontent.com/14098964/116057311-af144a80-a64c-11eb-8e01-b23eabbd494f.png)

**Comment by lladdy** [comment]
I suspect this might fix itself with a new session but points to some issue with our middleware maybe.
In the meantime, clearing your session or using a different browser might work.

**Comment by LostLucidity** [comment]
Clearing cookies and site data worked. Thank you!
