### ISSUE TITLE
Long bot names cause table rows to double in height

### ISSUE THREAD

**Issue by Immodal** [aiarena/aiarena-web#297]
Easy fix would be to truncate names beyond a certain length ending with "...".

We can also shorten the date to "17 Aug. 12:33" or something similar.

May want to look at tables in other pages as well to see if they need the same treatment.

![image](https://user-images.githubusercontent.com/13944193/130434933-f53db64c-6407-497b-a31f-cd18fa62cd60.png)

![image](https://user-images.githubusercontent.com/13944193/130434960-7a7bf004-f0da-4946-8b8c-de4285e9697c.png)

**Comment by Ketroc** [comment]
![image](https://user-images.githubusercontent.com/14032723/135135328-25db3b2f-dac5-4832-8a4e-356e2d2974fc.png)
Just an FYI that these long names cause formatting issues elsewhere as well (and if they get long enough, they'll cause the issue everywhere)

**Comment by Immodal** [comment]
The merged PR fixes all of that
