### ISSUE TITLE
Add content feed to front page

### ISSUE THREAD

**Issue by lladdy** [aiarena/aiarena-web#35]
Related to #34 
Add a feed for things like new youtube videos/community podcast.

**Comment by Mimz3598** [comment]
May i ask, do you mean that when you add something to your youtube channel, it will be displayed there? Or something like that?

**Comment by lladdy** [comment]
@Mimz3598 yes - that's one potential use.
I'd like for things happening in the community to be more apparent to everyone.
I'm hoping adding something to the front page for things like that will help people stay away of everything that's happening.
Other ideas could be upcoming events, tournaments, etc.

**Comment by Mimz3598** [comment]
> @Mimz3598 yes - that's one potential use.
> I'd like for things happening in the community to be more apparent to everyone.
> I'm hoping adding something to the front page for things like that will help people stay away of everything that's happening.
> Other ideas could be upcoming events, tournaments, etc.

I understand the intent, but as for the explicit source of the news.. will scraping be necessary or will there be some other input method provided?

**Comment by lladdy** [comment]
I expect it would change depending on the source. I would personally avoid scraping if possible.

For the purposes of this task, to keep it simple I would probably only expect an initial simple news source in order to establish the "content feed" in the first place - then later on get more fancy with YouTube integration, etc

An example might be creating a simple django model that just has a date and a text field that admins can manually enter content into (like a youtube link), and then having the list of those entries display on the content feed on the front page.

**Comment by Mimz3598** [comment]
Okey, so can I be assigned to this? I would love to try :)

**Comment by lladdy** [comment]
Sure can. Thanks for helping out :)
Shoot me a message if you can use any assistance

**Comment by Mimz3598** [comment]
![image](https://user-images.githubusercontent.com/58709776/95331863-e4249f80-08aa-11eb-8a7d-648297b2dbcc.png)

Could you please look into this? I followed instructions to get project working, but still no luck with nomodulefound: discord_bind

**Comment by eladyaniv01** [comment]
please make sure you follow the dev install instructions
looks like you did not do a recursive clone(  discord bind needs that) 
https://github.com/aiarena/aiarena-web/blob/staging/doc/INSTALL.md

**Comment by Mimz3598** [comment]
As i said, i am following theese instructuons and yes, i did recursive clone, even tryed git submodule update --init --recursive to be sure (even withou --init), but nothing changed.

**Comment by eladyaniv01** [comment]
can you please try 
`git fetch` 
`git pull --recurse-submodules` 
let me know if that works ?

**Comment by danielvschoor** [comment]
You will also need to rerun the pip to install discord-bind

**Comment by Mimz3598** [comment]
> You will also need to rerun the pip to install discord-bind

Thank you very much, this helped a lot! Didn't realize that i have to install it with pip.

**Comment by Mimz3598** [comment]
I am very sorry that i am so late, but until now there was too much happening, but i am going to work on the issue from today.

**Comment by lladdy** [comment]
@Mimz3598. Let us know if you need any help.

**Comment by Mimz3598** [comment]
May I ask, how do I create pull request? Which branch to use or am I supposed to create new one? I am sorry, it's really new for me.

**Comment by Mimz3598** [comment]
I created pull request, hope it's okey :-) .
