### ISSUE TITLE
BUG: Fidolina uploaded a new version of a bot,  while leaving the downloadable link unchecked,  but the bot is still downloadable

### ISSUE THREAD

**Issue by eladyaniv01** [aiarena/aiarena-web#43]
Also  going to profile -> edit  and saving with the download checkbox unchecked didnt work

**Comment by danielvschoor** [comment]
I can't reproduce this bug. Remember that all bots are downloadable for staff, so we can easier help debug. Try logging out and check if the bot is still doenloadable

**Comment by eladyaniv01** [comment]
you are right, i only asked the user to do the tests and send me info,  while ignoring the fact that the bot owner can download a bot even if it's not publicly downloadable
