### ISSUE TITLE
Change Date is Bot Results to "Started At" Date

### ISSUE THREAD

**Issue by Ketroc** [aiarena/aiarena-web#446]
A common use-case for the website, is to check matches from your latest bot update.  However, since the "Date" field in the "Results" list represents "Finished At" date, you can't reliably compare it to "Last Updated" date to know if the game was apart of the most recent update.  For this reason, I think making the "Date" column represent "Started At" Date would be more helpful.

![image](https://user-images.githubusercontent.com/14032723/187551082-d2f23b30-a1c5-4918-9569-07c60f3c29a1.png)

**Comment by lladdy** [comment]
This is a good point and I agree with this change.

Note for whoever implements this (likely me):
The match `Started` time will need to be updated each time an AC is re-served the match.

**Comment by Ketroc** [comment]
> The match `Started` time will need to be updated each time an AC is re-served the match.

Not sure what that means, but fyi that Start Time is already recorded on the match detail screen
![image](https://user-images.githubusercontent.com/14032723/187569456-3a82bc11-2a56-4720-89fd-afb040ce5e72.png)
