### ISSUE TITLE
Suggestion for League Ladder Structure

### ISSUE THREAD

**Issue by DrInfy** [aiarena/aiarena-web#63]
## Purpose & Motivation
Splitting ladder into leagues means more meaningful games for high ranked authors while also providing meaningful challenge for lower ranked author. This drives down costs while also keeping new authors more motivated when then they don't get matched with the ultra high end bots and end up having sub 10% win rate.

## Terminology
- League or league system replaces ladder as the system with all the bots playing melee mode
- Division is a part of the league with a group of bots taken from the whole league
- Premier league is the top division
- We can think of more interesting division names, but for this suggestion the names are: Premier league, Division 1, Division 2, Division 3, ...

## League Structure
When a season starts, all bots start at 1600 elo and in Premier league.
League splits and bot promotion/demotion between division happen at specified times each week (suggested time 0:00 Monday server time).

A single division should have a minimum of 20 bots and no more than 40 bots.

When the league reaches 40 bots, the league will split into two separate divisions: Premier league and Division 1. Premier league will have 20 top bots and Division 1 will have 20 bottom bots. Bot capacity for premier league will never fall down, but it will raise up to 30 bots until there are 50 active bots in the ladder. Bots will rise to Premier league based on the premier capacity based on their ranking on weekly rank up.

When there are 51 - 69 bots in the league, the league will have 2 division with Premier league hosting 30 bots and Division 1 having the rest. When the league reaches 70 bots, the Division 1 will split into Division 1 and Division 2 based on the bot rankings. Divisions that have split up, do not grow and instead stay with 20 bots per division. When division 2 reaches 40 bots, it splits up into Divisions 2 and 3. Division will continue splitting when there are 40 or more bots in a division.

## Bot promotion / demotion
Bot promotion happens each week on a specified time. Ranking within a division is based on ELO.
When divisions do not change their size and no bot leave, top bot from each league rises to next division while the bottom bot from each league drops to previous league. On top of this, divisions are filled with up to their maximum size, starting from the premier league. Bottom bot in a division is only demoted to lower division when the division is full. Bots ranked in 2nd and on are promoted to higher division until it is full. Bots not active in the ladder do not count for the division capacity. If a disabled bot is reactivated and the division goes over capacity, there will be equivalent amount of bots that drop to a lower division, but always a minimum of one bot will be promoted pre division.

## Matches / Round Robin
Matches are played in a round robin format within each division.

## New Bots
When a new bot joins the league after a season starts and when there is only one division, it will get a starting ELO of 1600 and join the Premier League. After the League has split into multiple divisions, the new bot will join lowest division and get a starting ELO of what is average in the lowest division.

## Bots leaving the ladder and bots going inactive
Bots not active in the ladder do not count for the league of division capacity. If a previously active bot rejoins the ladder, it's joining division will be decided by its ELO range. The ELO will be compared to lower division leader and if it is higher than that division leader, it will join that higher division.

## Edge cases
If the bot count drops, divisions don't automatically merge. Hopefully the divisions will not need to be merged.

**Comment by lladdy** [comment]
I really like this idea.
The only thing I'm not a huge fan of is the possibility for 2 bots to infinitely swap each week by being promoted/demoted.
But that's something we can address later as a refinement - this is already a great system, as far as I can tell.

**Comment by eladyaniv01** [comment]
looking into it right now

this is what comes to mind so far:

### Features

- Create **Competition** Model : 

- [ ]  with enum types such as  Tournament, Season, CustomEvent

     **_Any other important properties for this model ?_**

- Create **Division**  Model :

- [ ]  linked to a Competition ( common use case is divisions in a season)

- [ ]  Load balancing mechanism ( for when the number of active bots change,  reduce divisions or expand to more divisions)  ,  This might be split into smaller sub tasks 

- Modify **Bot** Model : 

- [ ]  can now "belong" to more than one Competition,  but only one Division per competition.

- [ ] Elo Decay formula for inactive bots

- **Frontend**

- [ ] timer until promotion demotion

- [ ] search filter division functionality 

- [ ] rework stat generator to accommodate seasons divisions and competitions 




- **seed.py**

- [ ] create dev database with a few Competitions(different types),  Divisions, and bots

  ### Tests / CI 

- [ ]  Test promotion demotion mechanism

- [ ] Test Elo Decay mechanism

- [ ] Test Load Balancing mechanism ( for divisions )
