### ISSUE TITLE
Setup website sentry monitoring

### ISSUE THREAD

**Issue by lladdy** [aiarena/aiarena-web#631]

**Comment by ipeterov** [comment]
Will be helpful to confirm that Celery is working - we can create a task that triggers an exception and run that task. If we get a notification from Sentry, it means that both Celery and Sentry are set up correctly.

**Comment by ipeterov** [comment]
We're now receiving notifications about:

- New, previously unseen issues
- Old issues that reappeared again after being marked as resolved
