### ISSUE TITLE
Migrate to PostgreSQL

### ISSUE THREAD

**Issue by danielvschoor** [aiarena/aiarena-web#7]
I'm creating this issue so that I can link to it from the Kanban board.

What are the thoughts around this?

Relevant tools:
[pgloader](https://pgloader.io/) 
[FromMySqlToPostgreSql](https://github.com/AnatolyUss/FromMySqlToPostgreSql)

**Comment by lladdy** [comment]
I guess we need to do this in steps.
Maybe the first step is to architect a repeatable translation of the data.
Then once we have that, we test locally with seed data to ensure it works and tests pass.
Then Update CI and then staging.
Test on staging using prod data.
Migrate prod.

Anything I missed?

**Comment by lladdy** [comment]
Done in #508
