### ISSUE TITLE
Add rank trend indication to the tables in the front page 

### ISSUE THREAD

**Issue by eladyaniv01** [aiarena/aiarena-web#90]
maybe an up / down arrow that updates every x amount of time  and indicates if a bot has moved up or down

**Comment by Immodal** [comment]
Hi, I would like to attempt this issue. 

One question I have is how would you store the bot positions for the before and after comparison? I ask because right now the Top 10 list just updates from the current state of SeasonParticipation.

Also, what would trigger this update?

Just FYI I'm new to django.

**Comment by eladyaniv01** [comment]
Hello, Thank you for your interest @Immodal , 
There are many interesting ways this could be done,  most of them involve javascript,  
However, to keep things simple,  at this point this feature will be only implemented in its basic for on the backend,

- [ ] Bot model should have a computed property that calculates the ratio of its current ELO and the one recorded in the last X hours (?)  this part should be dynamically modified when we need (maybe an interval with a time delta check)

- [ ] Update the relevant [template](https://github.com/aiarena/aiarena-web/blob/staging/aiarena/frontend/templates/index.html) to show the trend (you could use an icon of your choosing,  or even just `^` `v` 

how it looks is not the issue,   the functionality is.  we could re-design the UI  later if we want.

Let me know if you have any questions

**Comment by Immodal** [comment]
Thanks for the info @eladyaniv01.

I just added the functionality in my [fork](https://github.com/Immodal/aiarena-web/commit/b4157eb9a4a7cd57cb314800e93b222cf149e5bd). Does that look fine? The indicators now appear next to the ELO in the top 10 table. I tried to use material icons but I couldn't get the icon size to change to correctly fit table.

![image](https://user-images.githubusercontent.com/13944193/99471837-869c6c00-299b-11eb-8e4a-08b50cc631a0.png)

The only thing that needs to happen is a mechanism to update `trend_comparison_elo` in SeaspnParticipation periodically. Will you set that up or is that something I can do?

**Comment by eladyaniv01** [comment]
Looks good,  Great work @Immodal !
I will open another ticker with instructions as to how to update it ( i am considering on every round end) 
you could also do that one if you'd like, 
Next step is making sure the tests pass,  feel free to open a PR,
Thanks!

**Comment by Immodal** [comment]
I'd be happy to try it! I'll wait for the ticket.
