### ISSUE TITLE
Icons/badges/ribbons for trophies

### ISSUE THREAD

**Issue by lladdy** [aiarena/aiarena-web#93]
Suggested by mindme.

> some trophy icon/images would probably help
> Or even like military ribbons, where bots can build them up.

**Comment by Immodal** [comment]
Hi @lladdy , I'd like to attempt this issue. 

Can you give me some more detailed info as well as some guidance what you think should be done?

**Comment by lladdy** [comment]
@Immodal 
The coding side of this probably amounts to adding an image field to the Trophy model and updating the bot page template to display that image if it exists.
I've done a rough mock-up for you:
![image](https://user-images.githubusercontent.com/14326310/99903885-2c8f0400-2d17-11eb-8c3f-4a5e82aa7636.png)

The other side of this is sourcing decent icons we can use.

**Comment by lladdy** [comment]
Update: I have a friend who has access to a library of icons/images who might be able to help with sourcing said icons.

**Comment by Immodal** [comment]
I'll wait for you to get back to me then.

Also, is there a central list of trophies? Are trophies created automatically?

**Comment by lladdy** [comment]
No probs :)
Trophies are manually created in the django admin section.

**Comment by lladdy** [comment]
@Immodal I sent you some trophy icons in Discord
