### ISSUE TITLE
Competition, Division Models

### ISSUE THREAD

**Issue by eladyaniv01** [aiarena/aiarena-web#98]
- Create **Competition** Model : 

- [x]  With Enum types(property) such as  Tournament, Season, CustomEvent

- Create **Division**  Model :

- [x]  Linked to a Competition ( common use case is divisions in a season)

- Modify **Bot** Model : 

- [x]  Can now "belong" to more than one Competition,  but only one Division per competition.

**Comment by lladdy** [comment]
@eladyaniv01 I suggest moving each of these check list items into their related task issue.
e.g. put the competition model checkboxes in the multiladder issue and the division model checkbox in the division issue
